---
- name: Build a stonecutter SSO local machine
  hosts: stonecutter

  tasks:

    - name: Running update on pkg repositories
      apt: update_cache=yes
      run_once: true

    - name: Installing git, mongodb, libversioneer-clojure
      apt: name={{ item }} state=latest
      with_items:
        - libversioneer-clojure
        - mongodb
        - git
        - zsh

    - name: Create local bin folder
      file: path=/home/vagrant/bin state=directory owner=vagrant group=vagrant

    - name: Downloading lein
      get_url: dest="/home/vagrant/bin/lein" url=https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein mode=755 owner=vagrant group=vagrant

    - name: Cloning Stonecutter source
      git: repo=https://github.com/d-cent/stonecutter.git
           dest=/home/vagrant/stonecutter
      become: yes
      become_user: vagrant

    - name: add nodesource apt-key
      apt_key: url=https://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x1655A0AB68576280 state=present

    - name: add nodesource deb repo
      apt_repository: repo='deb https://deb.nodesource.com/node_0.12 trusty main' state=present

    - name: add nodesource deb-src repo
      apt_repository: repo='deb-src https://deb.nodesource.com/node_0.12 trusty main' state=present

    - name: install node.js
      apt: pkg=nodejs state=latest

    - name: install latest openssl
      apt: pkg=openssl state=latest

    - name: Node.js | Update npm
      command: npm install npm -g

    - name: symlink node->nodejs
      file: src=/usr/bin/nodejs dest=/usr/bin/node state=link

    - name: Node.js | Install packages
      npm: name={{item}} global=yes
      with_items:
        - npm
        - gulp

    - name: Node.js | Install dependencies
      shell: npm install
        chdir=/home/vagrant/stonecutter
      become: yes
      become_user: vagrant

    - name: Gulp | Build templates and styles
      shell: gulp build
        chdir=/home/vagrant/stonecutter
      become: yes
      become_user: vagrant
