---
- hosts: development
  remote_user: root
  
  tasks:
      # Running update on pre-installed packages
    - apt: update_cache=yes upgrade=full

      # Installing git, mongodb, libversioneer-clojure
    - apt: name={{ item }} state=latest
      with_items:
        - libversioneer-clojure
        - mongodb
        - git

      # reating freecoin group
    - group: name=freecoin state=present

      # reating freecoin user
    - user: name=freecoin 
            comment="freecoin user" 
            shell=/bin/bash 
            group=freecoin 
            home=/home/freecoin 
            createhome=yes 
            state=present	

      # copy lein install script
    - copy: src=./lein_install.sh dest=/tmp/lein_install.sh owner=root group=root mode=0755

      # run lein install script
    - command: /tmp/lein_install.sh
      args:
        chdir: /home/freecoin
        creates: /home/freecoin/.lein/self-installs/leiningen-2.5.3-standalone.jar 

      
