---
- hosts: development
  remote_user: root
  
  tasks:
    - name: Running update on pre-installed packages
      apt: update_cache=yes upgrade=full

    - name: Installing git, mongodb, libversioneer-clojure
      apt: name={{ item }} state=latest
      with_items:
        - libversioneer-clojure
        - mongodb
        - git

    - name: reating freecoin group
      group: name=freecoin state=present

    - name: Creating freecoin user
      user: name=freecoin 
            comment="freecoin user" 
            shell=/bin/bash 
            group=freecoin 
            home=/home/freecoin 
            createhome=yes 
            state=present	

    - block:
      # this part is being run under the freecoin user
      - name: Running lein install script
        script: ./lein_install.sh creates=/home/freecoin/.lein/self-installs/leiningen-2.5.3-standalone.jar 
      
      - name: Cloning the frecoin repository
        git: repo=https://github.com/d-cent/freecoin.git 
          dest=/home/freecoin/freecoin
          force=yes
      - name: Creating the jar
        shell: /home/freecoin/bin/lein uberjar >> lein_uberjar.log
        args:
          chdir: /home/freecoin/freecoin

      become: true
      become_user: freecoin

      # end of block
