---
- name: Build a vagrant machine with latest devuan, clone and build the freecoin jar
  hosts: staging_vm
  remote_user: root
  
  tasks:
    - name: Running update on pkg repositories
      apt: update_cache=yes 

    - name: Installing git, mongodb, libversioneer-clojure
      apt: name={{ item }} state=latest
      with_items:
        - libversioneer-clojure
        - mongodb
        - git
        - zsh

    - name: Creating freecoin group
      group: name=freecoin state=present

    - name: Creating staging user
      user: name={{ stg_user }} 
            comment={{ stg_user_comment }} 
            shell={{ stg_shell }}
            group={{ stg_group }}
            home={{ stg_homedir }}
            createhome=yes 
            state=present	

    - block:
      ## this part is being run under the freecoin staging user, might become a separate role in the future
      - name: Creating {{ stg_homedir }}/bin
        file: path="{{ stg_homedir }}/bin" state=directory mode=755

      - name: Downloading lein
        get_url: dest="{{ stg_homedir }}/bin/lein" url=https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein mode=750

      - name: Running lein for the first time
        command: chdir={{ stg_homedir }}/bin ./lein creates={{ stg_homedir }}/.lein/self-installs/leiningen-2.5.3-standalone.jar

      - name: Cloning the frecoin repository
        git: repo=https://github.com/d-cent/freecoin.git 
          dest="{{ stg_homedir }}/freecoin"
          force=yes

      - name: Creating the jar
        shell: "{{ stg_homedir }}/bin/lein uberjar >> lein_uberjar.log"
        args:
          chdir: "{{ stg_homedir }}/freecoin"

      become: true
      become_user: "{{ stg_user }}"
      ## end of block
